/* tslint:disable */
/* eslint-disable */
/**
 * Runtime
 * Runtime AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@runtime.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { StorageAccessDto } from '../models'
/**
 * ObjectStorageApi - axios parameter creator
 * @export
 */
export const ObjectStorageApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Get temporary storage access for pushing objects
     * @param {string} [xRuntimeOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPushAccess: async (
      xRuntimeOrganizationID?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/object-storage/push-access`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication oauth2 required

      if (xRuntimeOrganizationID != null) {
        localVarHeaderParameter['X-Runtime-Organization-ID'] = String(xRuntimeOrganizationID)
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * ObjectStorageApi - functional programming interface
 * @export
 */
export const ObjectStorageApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ObjectStorageApiAxiosParamCreator(configuration)
  return {
    /**
     *
     * @summary Get temporary storage access for pushing objects
     * @param {string} [xRuntimeOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getPushAccess(
      xRuntimeOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StorageAccessDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getPushAccess(xRuntimeOrganizationID, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ObjectStorageApi.getPushAccess']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * ObjectStorageApi - factory interface
 * @export
 */
export const ObjectStorageApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = ObjectStorageApiFp(configuration)
  return {
    /**
     *
     * @summary Get temporary storage access for pushing objects
     * @param {string} [xRuntimeOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPushAccess(xRuntimeOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<StorageAccessDto> {
      return localVarFp.getPushAccess(xRuntimeOrganizationID, options).then((request) => request(axios, basePath))
    },
  }
}

/**
 * ObjectStorageApi - object-oriented interface
 * @export
 * @class ObjectStorageApi
 * @extends {BaseAPI}
 */
export class ObjectStorageApi extends BaseAPI {
  /**
   *
   * @summary Get temporary storage access for pushing objects
   * @param {string} [xRuntimeOrganizationID] Use with JWT to specify the organization ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ObjectStorageApi
   */
  public getPushAccess(xRuntimeOrganizationID?: string, options?: RawAxiosRequestConfig) {
    return ObjectStorageApiFp(this.configuration)
      .getPushAccess(xRuntimeOrganizationID, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
